# Generated by Django 2.2.4 on 2019-10-04 19:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=tinymce.models.HTMLField(default='About author'),
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.FileField(blank=True, upload_to='author_imgs/'),
        ),
    ]
